import torch
from util.utils import get_device

TIME_STEPS = 100
DTYPE = torch.float
BATCH_SIZE = 32

HEIDELBERG_DATASET_NUMBER_CLASSES = 20

NUMBER_INPUT_NEURONS = 700
NUMBER_HIDDEN_NEURONS = 1000
NUMBER_OUTPUT_NEURONS = HEIDELBERG_DATASET_NUMBER_CLASSES
NUMBER_HIDDEN_LAYERS = 1

MAX_TIME = 1.4

BETA = 0.99
THRESHOLD = 1

DEVICE = get_device()

SPIKE_RATE_ESCAPE_BETA = 1
SPIKE_RATE_ESCAPE_SLOPE = 25

ATAN_ALPHA = 2