FLAGS = {
    'batch': 32,
    'lr_init': 0.01,
    'lr_decay': .3,
    'reg_rate': 10,
    'drop_out_probability': -1.,
    'tau_a': 200,
    'tau_v': 5,
    'thr': 1,
    'dt': 1.,
    'beta': 1.8,
    'n_regular': 500,
    'n_adaptive': 200,
    'n_layer': 1,
    'dampening_factor': 0.3,
    'n_ref': 2,
    'rec': True,
    "psp_out": True,
    "tau_out": 3,
    'l2': 1e-5,
    'adam_epsilon': 1e-5,
    "momentum": 0.9,
    'print_every': 100,
    'test_batch': 32,
    "reg": 50
}